version: "3.8"

services:
  simdatuk-cms2_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://10.1.53.220:8008/api"

    image: simdatuk-cms2:latest
    container_name: swp_simdatuk-cms2

    # environment:
    #   NODE_ENV: production

    restart: unless-stopped

    networks:
      - app-network

networks:
  app-network:
    external: true
