version: "3.8"

services:
  swp_simdatuknew_app:
    build:
      context: .
      dockerfile: Dockerfile

    image: swp_simdatuknew:latest
    container_name: swp_simdatuknew

    environment:
      NEXT_PUBLIC_API_URL: "http://10.1.53.220:8008/api"
      NODE_ENV: "production"

    restart: unless-stopped

    networks:
      - app-network

networks:
  app-network:
    external: true
